/**
 * Media URL rewriting — keeps Supabase Storage egress at ~zero.
 *
 * Images uploaded to the Supabase `media` bucket get public URLs on the
 * `*.supabase.co` domain. Served directly, every view is billed as Supabase
 * "cached egress" and bypasses Cloudflare entirely.
 *
 * We rewrite those URLs centrally (in `src/middleware.ts`, for all HTML) to:
 *   1. `/images/media/<file>.webp` — an optimized copy committed to /public and
 *      served free + cached by Cloudflare Pages. Used for every migrated image
 *      (see MEDIA_MANIFEST, generated by scripts/migrate-media-to-public.mjs).
 *   2. `/cdn/media/<key>` — an edge-cached proxy (src/pages/cdn/media/[...path].ts)
 *      for anything NOT migrated: PDFs (aqiqah certificates) and future uploads.
 *      Supabase serves those at most once per edge location, not per visitor.
 *
 * Doing it at the HTML layer means we don't have to touch the 35+ campaign
 * queries / 80+ render sites, and we never rewrite the database (which is shared
 * between prod and preview).
 */
import { MEDIA_MANIFEST } from './media-manifest';

const SUPABASE_URL = (import.meta.env.PUBLIC_SUPABASE_URL || '').replace(/\/$/, '');

/** e.g. https://epsjdbnxhmeprjrgcbyw.supabase.co/storage/v1/object/public/media/ */
export const SUPABASE_MEDIA_PREFIX = SUPABASE_URL
  ? `${SUPABASE_URL}/storage/v1/object/public/media/`
  : '';

/** Path fragment present in every storage public URL, used for a fast pre-check. */
const STORAGE_MARKER = '/storage/v1/object/public/media/';

/** Map a storage key (the part after .../media/) to its destination path. */
function destForKey(key: string): string {
  const local = MEDIA_MANIFEST[key];
  return local ? `/images/media/${local}` : `/cdn/media/${key}`;
}

/**
 * Convert a single Supabase media public URL into a local/proxied path.
 * Returns the input unchanged if it isn't a Supabase media URL.
 */
export function mediaUrl(url: string | null | undefined): string {
  if (!url || !SUPABASE_MEDIA_PREFIX) return url || '';
  if (!url.startsWith(SUPABASE_MEDIA_PREFIX)) return url;
  return destForKey(url.slice(SUPABASE_MEDIA_PREFIX.length));
}

/**
 * Absolute variant for contexts that can't use a relative path (e.g. email
 * bodies, opened off-site). `origin` should be the production origin.
 */
export function mediaUrlAbsolute(url: string | null | undefined, origin: string): string {
  const rel = mediaUrl(url);
  return rel.startsWith('/') ? `${origin}${rel}` : rel;
}

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * Rewrite every Supabase media URL in an HTML response body. Handles both plain
 * (`https://host/...`) and JSON-escaped (`https:\/\/host\/...`) forms, since
 * inline `<script>` JSON escapes slashes. No-ops for non-HTML responses and for
 * bodies that contain no storage URLs.
 */
export async function rewriteHtmlMediaUrls(res: Response): Promise<Response> {
  if (!SUPABASE_MEDIA_PREFIX) return res;

  const contentType = res.headers.get('content-type') || '';
  if (!contentType.includes('text/html')) return res;

  const body = await res.text();
  if (!body.includes(STORAGE_MARKER)) {
    return new Response(body, { status: res.status, statusText: res.statusText, headers: res.headers });
  }

  // A storage key runs until the next quote, paren, whitespace or backslash.
  // (Migrated image keys are flat — no internal slashes — so this is safe.)
  const plainRe = new RegExp(escapeRegExp(SUPABASE_MEDIA_PREFIX) + '([^"\'\\s)\\\\]+)', 'g');
  let out = body.replace(plainRe, (_m, key) => destForKey(key));

  // JSON-escaped form: prefix slashes appear as \/.
  const escapedPrefix = SUPABASE_MEDIA_PREFIX.replace(/\//g, '\\/');
  const escRe = new RegExp(escapeRegExp(escapedPrefix) + '([^"\'\\s)\\\\]+)', 'g');
  out = out.replace(escRe, (_m, key) => destForKey(key).replace(/\//g, '\\/'));

  const headers = new Headers(res.headers);
  headers.delete('content-length');
  return new Response(out, { status: res.status, statusText: res.statusText, headers });
}
